[[plugins]]
repo = 'Shougo/dein.vim'

#----------------------------------------------------------
# Aquires for running Neovim-plugins on Vim8
#----------------------------------------------------------
[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

#----------------------------------------------------------
# Auto-complete for F# script
#----------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'callmekohei/deoplete-fsharp'
build = 'bash install.bash'
hook_add = '''
    call deoplete#custom#option({
    \ 'auto_complete_delay': 0,
    \ 'ignore_case': v:true,
    \ })

    " remove duplicate candidates
    call deoplete#custom#source('_',
    \ 'converters', ['remove_overlap'])

    " Disable the candidates in Comment/String syntaxes.
    call deoplete#custom#source('_',
    \ 'disabled_syntaxes', ['Comment', 'String'])
'''

#----------------------------------------------------------
# Debug for F# script
#----------------------------------------------------------
[[plugins]]
repo = 'callmekohei/tigaDebugger'

#----------------------------------------------------------
# Run fsharp command
#----------------------------------------------------------
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    set splitright
    let g:quickrun_config = {}

    let g:quickrun_config._ = {
        \  'runner'                          : 'vimproc'
        \ ,'runner/vimproc/updatetime'       : 60
        \ ,'hook/time/enable'                : 1
        \ ,'hook/time/format'                : "\n*** time : %g s ***"
        \ ,'hook/time/dest'                  : ''
        \ ,"outputter/buffer/split"          : 'vertical'
        \ ,'outputter/buffer/close_on_empty' : 1
    \}

    let g:quickrun_config.fsharp = {
        \  'command'                         : 'fsharpi --readline-'
        \ ,'tempfile'                        : '%{tempname()}.fsx'
        \ ,'runner'                          : 'concurrent_process'
        \ ,'runner/concurrent_process/load'  : '#load "%S";;'
        \ ,'runner/concurrent_process/prompt': '> '
    \}
'''

#----------------------------------------------------------
# Show indent guide lines
#----------------------------------------------------------
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size = 1
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black ctermbg=0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=black ctermbg=0
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

